version: '3'
services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "80:80"
  backend:
    build: ./PHP
    ports:
      - "8000:8080"
  flask-app:
    build: ./flask-app
    ports:
      - "5000:5000"
